### ISSUE TITLE
wallet(new): Add Sonar to connect to Kujira Network

### ISSUE THREAD

**Issue by silvermind** [thorswap/SwapKit#385]
Sonar is Kujiras Mobile Wallet, which also supports Desktops (throught scanning a QR Code)
example at e.g. https://blue.kujira.network

https://docs.kujira.app/dapps-and-infrastructure/kujira-wallet/using-sonar

Here is a sample implementation in the kujira.ui library, seems based on walletconnect
https://github.com/Team-Kujira/kujira.ui/blob/main/src/wallets/sonar.ts

**Comment by chillios-dev** [comment]
@silvermind - not in capacity right now and no demand for now so closing as it's not gonna be taken by team. Happy to merge PR with new package but for now I don't see it implemented in upcoming year
