### ISSUE TITLE
[Wallet] XDefi wallet hasn't provider for Kujira chain.

### ISSUE THREAD

**Issue by yUradog** [thorswap/SwapKit#406]
can't connect Kujira chain using xdefi wallet.
there is a provider error to connect Kujira with xdefi wallet.

https://thorswap.github.io/SwapKit/
You can check the issue in your playground.

**Comment by chillios-ts** [comment]
@yUradog fixed in `@swapkit/wallet-xdefi@1.0.0-rc.40`

**Comment by yUradog** [comment]
hi, @chillios-ts , thx for updating.
![image](https://github.com/thorswap/SwapKit/assets/126171790/179c0dc8-d256-4a4e-b2cc-433f12f72fcc)

but still there is an error in playground.
Still there is something unclear for kujira chain using xdefi wallet.

**Comment by chillios-ts** [comment]
@yUradog you've tried too early 😅 refresh page and it should be now deployed in playground :)
