### ISSUE TITLE
toolbox(cosmos): registerThorname => registerMayaname

### ISSUE THREAD

**Issue by phips28** [thorswap/SwapKit#580]
There is currently a registerThorname() function.
Can you also create a registerMayaname() function?

**Comment by phips28** [comment]
I could take this in the next days 😉  we are also building an UI for it.

**Comment by mattgabriel** [comment]
> I could take this in the next days 😉 we are also building an UI for it.

Did you manage to look into this yet? 🙂

**Comment by phips28** [comment]
Didnt have time yet 🙈

**Comment by mattgabriel** [comment]
I'm also short with time, I could in a couple of weeks perhaps.

**Comment by phips28** [comment]
Starting now 😉
