### ISSUE TITLE
I am trying to Integrate the SwapKit in Our App 

### ISSUE THREAD

**Issue by kr-arunp** [thorswap/SwapKit#583]
I'm currently working on integrating SwapKit into my project, and I've come across a few challenges that I could use some guidance on. I've thoroughly reviewed the SDK code and explored the available APIs, but a couple of points are still unclear to me.
ThorName Integration:
        I'm trying to understand how to add our ThorName in the SDK. The provided example lacks integration for this feature, and I'm unsure about the correct approach.
     -where to get thorName (the mentioned website  in the doc is not working )
    Functionality Testing:
        How can we effectively test the functionalities of SwapKit? Is any testnet available for testing, I'm looking for insights into a suitable testing strategy.
    Service Fees :
        I'm also seeking clarity on the fees associated with using SwapKit. Specifically, I'd like to know about our affiliate fee and whether there's a 30% fee mentioned in the documentation (uncertain if this is included or not) 
If anyone has experience with these aspects of SwapKit or can provide guidance, I would greatly appreciate your insights. Additionally, i
Thank you in advance for your help!

**Comment by chillios-dev** [comment]
@kr-arunp Hi 👋
Some of the stuff is available both in docs of Thorchain(TC) & Thorswap(TS), but yes - we still lack of some documentation - especially on some niche features.

There is no testnet in TC (however there is stagenet - can be asked for access on TC discord.

THORNames (TNS) can be bought & extended via `registerThorname` or via some interfaces like TS
However you have to first check if this TNS is not taken (`SwapKitApi.getThornameRlookup` afaik)

There is no fee directly from using SwapKit, just from using TS API (fee is charged on swaps via affiliate fees).

The best is to discuss stuff over TS discord (in #swapkit-dev channel) as there is more team-members available to explain more in case of issue.

All links can be found there: https://linktr.ee/Thorchain

**Comment by kr-arunp** [comment]
Thank you @chillios-dev
