### ISSUE TITLE
Error submitting deposits on Maya

### ISSUE THREAD

**Issue by mattgabriel** [thorswap/SwapKit#682]
### Current behavior

All deposit transactions on the Maya chain are currently failing with the error below:

```
Error: Broadcasting transaction failed with code 6 (codespace: sdk). Log: all coins must be native to BASEChain: unknown request
at GA.broadcastTxSync
at async GA.broadcastTx
at async BA
at async Je$1.eval [as deposit]
```

### How to reproduce:

```
const client = createSwapKit();
await client.connectKeystore(Chain.Maya, phrase);
const hash = await client.deposit({
    assetValue: new AssetValue({
      value: 1,
      decimal: 10,
      chain: Chain.Maya,
      symbol: 'CACAO',
    }),
    memo: test,
    recipient: '',
});
```

Also fails when registering a MayaName since it also a deposit:

```
const hash = await client.registerMayaname({
  name: 'test1',
  chain: Chain.Maya,
  assetValue: new AssetValue({
    value: getMAYANameCost(1),
    decimal: 10,
    chain: Chain.Maya,
    symbol: 'CACAO',
  }),
  address: 'maya1.....',
});
```

### Expected behavior

It should work like it does for THORChain.

### Functionality

- [ ] Swap
- [ ] Liquidity
- [ ] Savers
- [ ] Loan
- [ ] Wallet
- [X] Transactions
- [ ] Api
- [ ] Other

### Packages

- [X] @swapkit/sdk
- [X] @swapkit/core
- [ ] @swapkit/api
- [ ] @swapkit/helpers
- [ ] @swapkit/tokens
- [ ] @swapkit/types
- [X] @swapkit/toolbox-cosmos
- [ ] @swapkit/toolbox-evm
- [ ] @swapkit/toolbox-utxo
- [ ] @swapkit/wallet-evm-extensions
- [ ] @swapkit/wallet-keepkey
- [ ] @swapkit/wallet-keplr
- [ ] @swapkit/wallet-keystore
- [ ] @swapkit/wallet-ledger
- [ ] @swapkit/wallet-okx
- [ ] @swapkit/wallet-trezor
- [ ] @swapkit/wallet-wc
- [ ] @swapkit/wallet-xdefi

### Details

Package versions:
```bash
# Paste the output of `<npm|yarn|pnpm|bun pm> ls --depth=0 | grep @swapkit` here
```

**Comment by chillios-dev** [comment]
@mattgabriel could you try with newest version? We currently testing Maya and it seems working fine for actions 🤔
