### ISSUE TITLE
Missing Memos

### ISSUE THREAD

**Issue by Rotwang9000** [thorswap/SwapKit#899]
### Current behavior

```
		const txData = {
			assetValue: assetValue,
			recipient: recipientAddress,
			from: sendingWallet.address,
			feeOptionKey: FeeOption.Average,
			chain: selectedToken.chain,
			memo: memo
		};
		console.log('Sending funds:', txData, sendingWallet);

			const txID = await skClient.transfer(txData);
```

The console logs:
```
assetValue: 
G { decimalMultiplier: 100000000n, bigIntValue: 100000000n, decimal: 8, address: undefined, chain: 'THOR', … }
chain:
"THOR"
feeOptionKey:
"average"
from:
"thor17a2dfukaum4f0c2dxvjw37mn35c2yal2yhqzyd"
memo:
"ABC100588119"
recipient:
"thor1wr4r0hw7apejj76xlxfxaw86r2v7r0ehl5sqg2"

```
...but no memo is in the transaction

https://runescan.io/tx/6499DC43CF707104FD655777973A4395708CB61362A7DEC174DF2AAB20319A9E

### Expected behavior

The transaction to include the provided memo

### Functionality

- [ ] Swap
- [ ] Liquidity
- [ ] Savers
- [ ] Loan
- [ ] Wallet
- [X] Transactions
- [ ] Api
- [ ] Other

### Packages

- [X] @swapkit/sdk
- [X] @swapkit/core
- [ ] @swapkit/api
- [ ] @swapkit/helpers
- [ ] @swapkit/tokens
- [ ] @swapkit/toolbox-cosmos
- [ ] @swapkit/toolbox-evm
- [ ] @swapkit/toolbox-utxo
- [ ] @swapkit/wallet-evm-extensions
- [ ] @swapkit/wallet-keepkey
- [ ] @swapkit/wallet-keplr
- [X] @swapkit/wallet-keystore
- [ ] @swapkit/wallet-ledger
- [ ] @swapkit/wallet-okx
- [ ] @swapkit/wallet-trezor
- [ ] @swapkit/wallet-wc
- [ ] @swapkit/wallet-xdefi

### Details

Package versions:
```bash
├── @swapkit/plugin-chainflip@1.0.3
├── @swapkit/sdk@1.0.3
├── @swapkit/tokens@1.0.1
├── @swapkit/toolbox-radix@1.0.3
├── @swapkit/toolbox-substrate@1.0.3
```

**Comment by Rotwang9000** [comment]
Can someone confirm if they are having the same problem, or if it's just me? Thanks.

**Comment by Rotwang9000** [comment]
Anyone?!

**Comment by ice-chillios** [comment]
@Rotwang9000 - Not really - we are sending custom memos via `.transfer` method as well but will try to take a look this week for that on playground.

**Comment by Rotwang9000** [comment]
Sorry forgot to close this... @towanTG helped me with a workaround (using client.getWallet(chain).transfer() ) but think it is fixed now anyways
