### ISSUE TITLE
Swapkit SDK Swapping Bug

### ISSUE THREAD

**Issue by kamalbuilds** [thorswap/SwapKit#908]
### Current behavior

ModuleDependencyError: export 'getMemoForNamePreferredAssetRegister' (imported as 'j1') was not found in '@swapkit/helpers' (possible exports: AGG_SWAP, ApproveMode, AssetValue, BaseDecimal, BigIntArithmetics, Chain, ChainId, ChainIdToChain, ChainToChainId, ChainToExplorerUrl, ChainToHexChainId, ChainToRPC, CommonAssetStrings, ContractAddress, CosmosChains, DerivationPath, EVMChains, EVMTransactionDetailsParamsSchema, EVMTransactionDetailsSchema, EstimatedTimeSchema, ExplorerUrl, FeeOption, FeeTypeEnum, FeesSchema, LedgerErrorCode, MAYASupportedChains, MayaArbitrumVaultAbi, MayaEthereumVaultAbi, MemoType, NetworkDerivationPath, ProviderName, QuoteMode, QuoteRequestSchema, QuoteResponseSchema, RPCUrl, RequestClient, RouteLegSchema, RouteLegWithoutAddressesSchema, RouteQuoteLegSchema, RouteQuoteMetadataAssetSchema, RouteQuoteMetadataSchema, RouteQuoteSchema, RouteQuoteWarningSchema, SWAP_IN, SWAP_OUT, SubstrateChains, SwapKitError, SwapKitNumber, TCAvalancheDepositABI, TCBscDepositABI, TCEthereumVaultAbi, TCSupportedChains, UTXOChains, WalletOption, WarningCodeEnum, addAccountsChangedCallback, addEVMWalletNetwork, assetFromString, defaultRequestHeaders, derivationPathToString, erc20ABI, filterAssets, findAssetBy, formatBigIntToSafeValue, getAssetType, getAsymmetricAssetShare, getAsymmetricAssetWithdrawAmount, getAsymmetricRuneShare, getAsymmetricRuneWithdrawAmount, getChainIdentifier, getCommonAssetInfo, getDecimal, getDerivationPathFor, getEIP6963Wallets, getETHDefaultWallet, getEstimatedPoolShare, getGasAsset, getLiquiditySlippage, getMAYANameCost, getMemoFor, getMemoForDeposit, getMemoForLeaveAndBond, getMemoForLoan, getMemoForNameRegister, getMemoForSaverDeposit, getMemoForSaverWithdraw, getMemoForUnbond, getMemoForWithdraw, getMinAmountByChain, getSymmetricPoolShare, getSymmetricWithdraw, getTHORNameCost, getWalletFormatFor, isDetected, isGasAsset, isWeb3Detected, listWeb3EVMWallets, okxMobileEnabled, prepareNetworkSwitch, setRequestClientConfig, switchEVMWalletNetwork, validateIdentifier, validateTNS, warnOnce, wrapMethodWithNetworkSwitch, wrapWithThrow)

![image](https://github.com/user-attachments/assets/d44463cc-2ea2-4bcb-8a21-95c70159e3ef)

### Expected behavior

This error should not come

### Functionality

- [X] Swap
- [ ] Liquidity
- [ ] Savers
- [ ] Loan
- [ ] Wallet
- [ ] Transactions
- [ ] Api
- [ ] Other

### Packages

- [X] @swapkit/sdk
- [ ] @swapkit/core
- [ ] @swapkit/api
- [X] @swapkit/helpers
- [ ] @swapkit/tokens
- [ ] @swapkit/toolbox-cosmos
- [ ] @swapkit/toolbox-evm
- [ ] @swapkit/toolbox-utxo
- [ ] @swapkit/wallet-evm-extensions
- [ ] @swapkit/wallet-keepkey
- [ ] @swapkit/wallet-keplr
- [ ] @swapkit/wallet-keystore
- [ ] @swapkit/wallet-ledger
- [ ] @swapkit/wallet-okx
- [ ] @swapkit/wallet-trezor
- [ ] @swapkit/wallet-wc
- [ ] @swapkit/wallet-xdefi

### Details

Package versions:
```bash
# Paste the output of `<npm|yarn|pnpm|bun pm> ls --depth=0 | grep @swapkit` here
```
    "@swapkit/core": "^1.1.1",
    "@swapkit/plugin-chainflip": "^1.1.1",
    "@swapkit/plugin-thorchain": "^1.1.1",
    "@swapkit/sdk": "^1.1.2",
    "@swapkit/tokens": "^1.0.1",
    "@swapkit/wallet-coinbase": "^1.0.6",
    "@swapkit/wallet-evm-extensions": "^1.0.6",
    "@swapkit/wallet-keplr": "^1.0.6",
    "@swapkit/wallet-keystore": "^1.0.6",
    "@swapkit/wallet-wc": "^1.0.6",
    "@swapkit/wallet-xdefi": "^1.0.6",

**Comment by kamalbuilds** [comment]
@chillios-dev Please help fix this error , stuck at this from many hours

**Comment by ice-chillios** [comment]
@kamalbuilds try newest build versions - it seems like `@swapkit/helpers` didn't release properly with rest packages

**Comment by kamalbuilds** [comment]
@chillios-dev theres one more coming from inside the packages.

![image](https://github.com/user-attachments/assets/477ec5ab-8195-43ad-aee9-a848a3209a12)

**Comment by kamalbuilds** [comment]
By debugging I found it to occur from this file , https://github.com/thorswap/SwapKit/blob/develop/packages/wallets/keystore/src/keystore.ts#L253

**Comment by ice-chillios** [comment]
The core of this issue has been resolved - if there are any new ones - please create new issue with info of versions used and setup of framework with code samples
