### ISSUE TITLE
Swapkit SDK has errors

### ISSUE THREAD

**Issue by kamalbuilds** [thorswap/SwapKit#914]
### Current behavior

Keystore wallet has a bug in the package publishing

![WhatsApp Image 2024-07-16 at 23 37 47_9c01c31d](https://github.com/user-attachments/assets/cb40f48d-d5d9-48a0-9271-bd4d70f11c31)

### Expected behavior

The global error should not come.

### Functionality

- [X] Swap
- [X] Liquidity
- [X] Savers
- [X] Loan
- [X] Wallet
- [X] Transactions
- [X] Api
- [ ] Other

### Packages

- [ ] @swapkit/sdk
- [ ] @swapkit/core
- [ ] @swapkit/api
- [ ] @swapkit/helpers
- [ ] @swapkit/tokens
- [ ] @swapkit/toolbox-cosmos
- [ ] @swapkit/toolbox-evm
- [ ] @swapkit/toolbox-utxo
- [ ] @swapkit/wallet-evm-extensions
- [ ] @swapkit/wallet-keepkey
- [ ] @swapkit/wallet-keplr
- [X] @swapkit/wallet-keystore
- [ ] @swapkit/wallet-ledger
- [ ] @swapkit/wallet-okx
- [ ] @swapkit/wallet-trezor
- [ ] @swapkit/wallet-wc
- [ ] @swapkit/wallet-xdefi

### Details

Package versions:
```bash
# Paste the output of `<npm|yarn|pnpm|bun pm> ls --depth=0 | grep @swapkit` here
```

**Comment by kamalbuilds** [comment]
@mogarchy

**Comment by kamalbuilds** [comment]
@mogarchy @chillios-dev can you please look into this error and fix it ?

**Comment by Rotwang9000** [comment]
I came across this.. my solution was to define it

in my webpack.config.js...

```
const rdm = Math.floor(Math.random() * 10).toString();
window.global = {
    rdm: rdm,
};
```

**Comment by ice-chillios** [comment]
@kamalbuilds it's related to next.js building with webpack - check nextjs playground for those issues as it's there definitely to copy - I will prepare docs for different frameworks this week
