### ISSUE TITLE
Maya Protocol shortcodes

### ISSUE THREAD

**Issue by GiMa-Maya** [thorswap/SwapKit#915]
### Requested functionality area

- [ ] Wallet
- [ ] Chain
- [X] Provider
- [ ] Other

### Details

Streaming swaps are in public stagenet for Maya now. We have added the following shortcodes:
https://gitlab.com/mayachain/mayanode/-/issues/17#note_1857981575
<img width="556" alt="Screenshot 2024-07-19 at 14 06 47" src="https://github.com/user-attachments/assets/dddfbe6c-606d-4b9e-a8b7-8f15fdcec059">

**Comment by olegpetroveth** [comment]
I will take care of backend part!

**Comment by GiMa-Maya** [comment]
#916

**Comment by GiMa-Maya** [comment]
Streaming is live! Leggooo

**Comment by ice-chillios** [comment]
@olegpetroveth I assume we need to add those codes to backend generation list right? as tokens should automatically update with one 🤔
