### ISSUE TITLE
May I take over leap wallet on SDK?

### ISSUE THREAD

**Issue by promisingdev425** [thorswap/SwapKit#995]
### Requested functionality area

- [ ] Wallet
- [ ] Chain
- [ ] Provider
- [ ] Other

### Details

@ice-chillios 

I am a Web3 full stack developer and want to contribute to SDK project.

**Comment by ice-chillios** [comment]
@promisingdev425 sure, we had no plans in upcoming month to do so.
BTW. you could comment a main issue #379 😅
